spring:
  application:
    name: Event Generator

  profiles:
    active: ${SPRING_APPLICATION_PROFILE:production}

  datasource:
    url: jdbc:${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
