on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Image
        run: docker build -t ${secrets.DOCKER_USER}/event-manager .
      - name: Docker login
        run: docker login -u ${secrets.DOCKER_USER} -p ${secrets.DOCKER_PASSWORD}
      - name: Docker push
        run: docker push ${secrets.DOCKER_USER}/event-manager
